AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Digital team Lambda functions

Parameters:
  LambdaStackName:
    Type: String
    Description: Parent stack name, used for naming

  LambdaExecutionRoleArn:
    Type: String
    Description: ARN for the role that Lambda functions will get

Resources:
  CloudFormationDeployFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${LambdaStackName}-CloudFormationDeployFunction"
      Description: Function to notify Slack when a CloudFormation deploy completes
      Role: !Ref LambdaExecutionRoleArn
      Handler: post-cloudformation-deploy.handler
      Runtime: nodejs6.10
      CodeUri: ./slack/
